DEBUG = True
TITLE = 'Photo albums'
FRONTEND_HOST = '127.0.0.1'
FRONTEND_PORT = 5050
FRONTEND_BASEURL = 'http://showoff'
FRONTEND_PREFIX = '/showoff'
FRONTEND_FCGI_SOCKET = '/tmp/showoff.frontend.sock'
ADMIN_HOST = '127.0.0.1'
ADMIN_PORT = 5051
ADMIN_BASEURL = 'http://showoff'
ADMIN_PREFIX = '/showoff_admin'
ADMIN_FCGI_SOCKET = '/tmp/showoff.admin.sock'
THUMBNAIL_SIZE = 400
GRID_SIZE = 200
ADMIN_THUMBNAIL_SIZE = 400
THUMBNAILS_PER_PAGE = 40
THUMBNAILS_PER_SMALL_LIST = 8
ADMIN_THUMBNAILS_PER_PAGE = 12
ADMIN_GRID_ITEMS_PER_PAGE = 50
FRONTEND_GRID_ITEMS_PER_PAGE = 50
IMAGE_SIZE = 800
ALLOWED_SIZES = [ 75, 200, 400, 500, 640, 800, 1024, 1600, 'full' ]
THEME = 'v2'
ADMIN_THEME = 'v2'
CACHE_DIR = '../lib/showoff/cache'
EDITS_DIR = '../lib/showoff/edits'
SHOWS_DIR = '../lib/showoff/shows'
SECRET_KEY = 'CHANGE_THIS'
ALBUMS_DIR = '../lib/showoff/photos'
FRONTEND_LIST_TEMPLATES = ['list', 'list_small', 'grid', 'galleria']

